spring.application.name=demo

spring.datasource.url=jdbc:mysql://cis-307-mysql.ad.northscott.net:3306/libraryIF
spring.datasource.username=I_Farley
spring.datasource.password=Password123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080